spring.application.name=product-service
server.port=8088

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.enabled=true

# Bu yerdagi redis va db malumotlarni ishlatish shart emas hammasi compose.yml ichida yozilgan
# Localda test qilb ishlatish uchun pastdagi commentlar ochilsa boldi
# Agar dockerga chiqarmoqchi bolsa localhost o'rniga compose ichidagi service name lar

#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:postgresql://localhost:5433/appdb
#spring.datasource.username=myuser
#spring.datasource.password=mypassword

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

